### ISSUE TITLE
6DOF quaternion based EKF

### ISSUE THREAD

**Issue by HSafy** [pms67/EKF-Quaternion-Attitude-Estimation#1]
If I understand it right, If I had only the the accelerometer without the magnetometer then the C matrix ( observation) would change by removing the last 3 rows. Moreover , what if I didn't have the Va ? how the accelerometer model look like then ? should I just assume it to be zero ? 
I mean I only have the accelerometer in my update step. 
Thanks 

and by the way .. great work !

**Comment by pms67** [comment]
Hi there,

Yes, if you only have a gyroscope and an accelerometer, the output function would only consist of z = [ax, ay, az] and thus the Jacobian C would be a 3x4 matrix - as you said by removing the last three rows.

If you don’t have an airspeed measurement (Va), the simplest method is indeed to set Va to 0.0. The state estimates will be degraded but still usable.

I hope that helps.

Best,
Philip

Note: Also, having no airspeed measurement and no magnetometer will impact the observability of the gyro biases.

**Comment by araujokth** [comment]
Hi @pms67, I was reading your answer on this issue and C should become a 3x7 matrix, not 3x4 right? Since the # of columns of C should be the same as the state vector

**Comment by simon88** [comment]
Is it possible to have an example about this?
